version: 0.1
phases:
  build:
    commands:
      - npm install
      - npm test
artifacts:
  files:
    - index.html
    - favicon.ico
    - Manish_CV.pdf
    - styles/*
    - images/*
    - dist/bundle.js
